
  services:
    postgres:
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: userservice
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - app-network
  networks:
    app-network:
      driver: bridge
  volumes:
    postgres_data: